config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts
  resources :tags
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record Class
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_and_belongs_to_many :tags
  has_rich_text :body
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save!
      redirect_to action: :index
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:success] = 'Post edited successfully'
      redirect_to action: :index
    else
      flash[:alert] = @post.errors.full_messages
      redirect_to action: :edit, id: params[:id]
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, tag_ids: [])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @posts = @tag.posts
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper Module
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/blog/index.html.erb
<div class="container">
  <div class="text-center">
    <%= link_to root_path, class: 'no-decoration' do %>
      <%= image_tag 'logo.png', class: 'logo-image' %>
      <h3>
        The Grati Dev
      </h3>
    <% end %>
    <p>
      <%= link_to root_path, class: 'no-decoration' do %> A blog by <% end %> <%= link_to '@behraaang', TWITTER, class: 'with-decoration' %> about Ruby, Elixir, React etc.
    </p>
  </div>

  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8 text-center main">
      <%= render @posts %>
    </div>
    <div class="col-sm-2"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>

  </head>

  <body>
    <div class="container">
      <div class="text-center">
        <%= link_to root_path, class: 'no-decoration' do %>
          <% is_root = controller_name == 'posts' && action_name == 'index' %>
          <%= image_tag 'logo.png', class: is_root ? 'logo-image' : 'logo-image-small' %>
          <h2 class="<%= is_root ? '' : 'small' %>">
            The Grati Dev
          </h2>
        <% end %>
      </div>
      <%= yield %>

      <div class="row text-center footer">
        <div>
          <%= t('footer.main') %>
        </div>
        <div>
          <%= t('footer.p') %>
        </div>
      </div>

    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="form-group">
    <div>Title</div>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field">
    <div>Body</div>
    <%= f.rich_text_area :body, class: 'form-control customized-min-height', placeholder: "Enter your article body here..." %>
  </div>
  <div class="form-group">
    <div>Tags</div>
    <%= f.select :tag_ids, Tag.all.map{|t| [t.name, t.id] }, {}, :multiple => true %>
  </div>
  <%=f.submit %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to post.title, post_path(id: post.id), style: 'font-size: 30px', class:'with-decoration' %><br />
<span class="text-small">
  <%= post.created_at.strftime('%B %d, %Y') %>.
  <% if post.tags.any? %>
    Tagged
    <% post.tags&.each do |tag| %>
      <%= link_to(tag.name, tag_path(id: tag.id), class:'with-decoration') %>
    <% end %>
  <% end %>
</span>
<br />

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="text-center">
  <p>
    <%= link_to root_path, class: 'no-decoration' do %> <%= t('posts.p1') %> <% end %>
    <%= link_to '@behraaang', TWITTER, class: 'with-decoration' %>
    <%=t('posts.p2') %> <%= link_to 'Ruby', tag_path(id: Tag.where(name: 'Ruby').first_or_create.id), class: 'with-decoration' %>,
    <%= link_to 'Elixir', tag_path(id: Tag.where(name: 'Elixir').first_or_create.id), class: 'with-decoration' %>,
    <%= link_to 'React', tag_path(id: Tag.where(name: 'React').first_or_create.id), class: 'with-decoration' %>
    <%= link_to 'etc', tag_path(id: Tag.where(name: 'etc').first_or_create.id), class: 'with-decoration' %>.
  </p>
</div>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 main">

    <%= render @posts %>

  </div>
  <div class="col-sm-3"></div>
</div>

app/views/posts/new.html.erb
<h2>New Post</h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<div class="text-center">
  <h3>
    <%= link_to @post.title, post_path(id: @post.id), class: 'no-decoration' %>
  </h3>
  <small>
    Written <%= @post.created_at.strftime('%B %d, %Y') %>.
    <% if @post.tags.any? %>
      Tagged
      <% @post.tags&.each do |tag| %>
        <%= link_to(tag.name, tag_path(id: tag.id), class:'with-decoration') %>
      <% end %>
    <% end %>
  </small>
</div>

<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-sm-8 main">
    <%= @post.body %>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/tags/show.html.erb
<div class="text-center">
  <h3>
    <%= link_to @tag.name, tag_path(id: @tag.id), class: 'no-decoration' %>
  </h3>
</div>

<div class="row">
  <div class="col-sm-3"></div>
  <div class="col-sm-6 main">

    <%= render @posts %>

  </div>
  <div class="col-sm-3"></div>
</div>